---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get incidents
      servicenow.itsm.incident_info:
        instance:
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
          host: "{{ snow_instance }}"
 
      register: result