---
- name: Register new CMDB instance
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Simulate VM creation
      ansible.builtin.set_fact:
        cmdb_item:
          name: vm-360
          id: vm360
          public_ip_address: 10.0.0.100

    - name: Register the newly-created VM instance
      servicenow.itsm.configuration_item:
        instance:
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
          host: "{{ snow_instance }}"        
        name: "{{ cmdb_item.name }}"
        sys_class_name: cmdb_ci_vm_instance
        ip_address: "{{ cmdb_item.public_ip_address }}"
        other:
          vm_inst_id: "{{ cmdb_item.id }}"
