---
- name: Check RHEL security packages
  hosts: all
  gather_facts: yes
  collections:
    - servicenow.servicenow
  vars:
    dnf_check: true
    dnf_security: true

  tasks:
  - name: Check RHEL packages for security
    command: /bin/dnf check-update --security
    args:
      warn: no
    become: yes
    register: check_update
    failed_when: check_update.rc == 1
    changed_when: check_update.rc == 100
    until: check_update is not failed
    retries: 5
    when: dnf_check | bool and dnf_security | bool

  - name: Create new incident
    snow_record:
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: incident
      data:
        short_description: "SECURITY COMPLIANCE - Package updates needed on {{inventory_hostname}}"
        severity: 3
        priority: 2
        caller_id: "System Administrator"
        comments: "--------\n SECURITY COMPLIANCE \n--------\n Updates needed on {{inventory_hostname}}"      
    register: snow_var
    delegate_to: localhost
    when: check_update.rc == 100

