---
- name: Check Windows security packages
  hosts: all
  gather_facts: yes
  collections:
    - servicenow.servicenow
  vars:

  tasks:
  - name: Check Windows packages for security
    win_updates:
      category_names: DefinitionUpdates
      state: searched
    register: check_update
#    failed_when: check_update.rc == 1
#    changed_when: check_update.found_update_count > 0
    retries: 5

  - name: Create new incident
    snow_record:
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: incident
      data:
        short_description: "SECURITY COMPLIANCE - Windows Definition updates needed on {{inventory_hostname}}"
        severity: 3
        priority: 2
        caller_id: "System Administrator"
        comments: "--------\n SECURITY COMPLIANCE \n--------\n Definition Updates needed on {{inventory_hostname}}"      
    register: snow_var
    delegate_to: localhost
    when: check_update.found_update_count > 0

